version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teambuilding
      MYSQL_USER: user
      MYSQL_PASSWORD: MyPassword123.
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./data-init:/docker-entrypoint-initdb.d
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - webnet

volumes:
  db_data:
    driver: local

networks:
  webnet: